apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
  namespace: gitlab-operator
spec:
  chart:
    version: 9.8.8
    values:
      global:
        puma:
          workerProcesses: 2
          minThreads: 1
          maxThreads: 4
        hosts:
          domain: k0s.mdoktor.foo
          gitlab:
            name: gitlab.k0s.mdoktor.foo
            https: false
          registry:
            name: registry.k0s.mdoktor.foo
            https: false
          minio:
            name: minio.k0s.mdoktor.foo
            https: false
          smartcard:
            name: smartcard.k0s.mdoktor.foo
          kas:
            name: kas.k0s.mdoktor.foo
          pages:
            name: pages.k0s.mdoktor.foo
            https: false
          ssh: gitlab.k0s.mdoktor.foo
        ingress:
          configureCertmanager: false
          class: traefik
          tls:
            enabled: true
            secretName: gitlab-tls
        rails:
          bootsnap:
            enabled: false
        shell:
          port: 32022
      registry:
        enabled: false
      pages:
        enabled: false
        kas:
          enabled: false
      smartcard:
        enabled: false
      installCertmanager: false
      nginx-ingress:
        enabled: false
      prometheus:
        install: false
      gitlab-runner:
        install: true
      gitlab:
        webservice:
          minReplicas: 1
          maxReplicas: 1
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          env:
            GITLAB_MAX_THREADS: 4
        sidekiq:
          minReplicas: 1
          maxReplicas: 1
          concurrency: 5
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          queues:
            - critical
            - default
          env:
            SIDEKIQ_CONCURRENCY: 5
        gitlab-shell:
          minReplicas: 1
          maxReplicas: 1
          service:
            type: NodePort
            nodePort: 32022
        gitlabRails:
          memoryCacheSize: "64MB"
