apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "git@github.com:Mikkelmedetk/k0s.git"
    targetRevision: main
    path: "environments/prod"
    directory:
      recurse: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
