apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  # - path: namespace-patch.yaml
  #   target:
  #     kind: Namespace
  #     name: gitlab-operator
  #     version: v1
  - path: operator-group-patch.yaml
    target:
      kind: OperatorGroup
      name: operatorgroup
      group: operators.coreos.com
      version: v1
  - path: subscription-patch.yaml
    target:
      kind: Subscription
      name: gitlab-operator-subscription
      group: operators.coreos.com
      version: v1alpha1
commonLabels:
  environment: prod
  argocd.argoproj.io/managed-by: argocd
